import { defineConfig } from "vitest/config";
import path from "path";

const templateRoot = path.resolve(import.meta.dirname);

export default defineConfig({
  root: templateRoot,
  resolve: {
    alias: {
      "@": path.resolve(templateRoot, "client", "src"),
      "@shared": path.resolve(templateRoot, "shared"),
      "@assets": path.resolve(templateRoot, "attached_assets"),
    },
  },
  test: {
    environment: "node",
    // electron/ holds the desktop business rules (incident transitions, record
    // validation) and was previously excluded, so its suite never ran.
    include: ["server/**/*.test.ts", "server/**/*.spec.ts", "electron/**/*.test.ts"],
    // desktop-app/ is generated by scripts/stage-desktop.mjs — a copy of
    // electron/, so collecting it would run every test twice.
    exclude: ["**/node_modules/**", "**/dist/**", "desktop-app/**"],
  },
});
