import { defineConfig } from "vitest/config";
import path from "path";

const templateRoot = path.resolve(import.meta.dirname);

export default defineConfig({
  root: templateRoot,
  // Vitest transforms TSX with esbuild directly (no @vitejs/plugin-react here),
  // whose default is the classic runtime — every component would need a manual
  // `import React`. The automatic runtime matches how Vite builds the app.
  esbuild: { jsx: "automatic" },
  resolve: {
    alias: {
      "@": path.resolve(templateRoot, "client", "src"),
      "@shared": path.resolve(templateRoot, "shared"),
      "@assets": path.resolve(templateRoot, "attached_assets"),
    },
  },
  test: {
    environment: "node",
    // electron/ holds the desktop business rules (incident transitions, record
    // validation) and was previously excluded, so its suite never ran.
    include: [
      "server/**/*.test.ts",
      "server/**/*.spec.ts",
      "electron/**/*.test.ts",
      "client/src/**/*.test.ts",
      "client/src/**/*.test.tsx",
    ],
    // Component tests get a DOM; the pure-logic suites stay in node, which is
    // faster and keeps them honest about not touching the browser.
    environmentMatchGlobs: [["client/src/**/*.component.test.tsx", "jsdom"]],
    // desktop-app/ is generated by scripts/stage-desktop.mjs — a copy of
    // electron/, so collecting it would run every test twice.
    exclude: ["**/node_modules/**", "**/dist/**", "desktop-app/**"],
  },
});
