import { Clock3, Download, ShieldCheck, Stethoscope, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { OpsRecord, formatDate } from "@/lib/ops";
import { Textarea } from "@/components/ui/textarea";
import { useState } from "react";

function Header({ eyebrow, title, onClose }: { eyebrow: string; title: string; onClose: () => void }) { return <div className="flex items-start justify-between border-b border-slate-800 px-6 py-5"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-cyan-300">{eyebrow}</p><h2 className="mt-1 text-xl font-semibold text-white">{title}</h2></div><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-800 hover:text-white" aria-label="Close detail"><X className="h-5 w-5" /></button></div>; }
function Drawer({ children }: { children: React.ReactNode }) { return <aside className="fixed inset-y-0 right-0 z-40 flex w-full max-w-xl flex-col border-l border-slate-700 bg-[#101827] shadow-[-22px_0_65px_rgba(0,0,0,0.45)]">{children}</aside>; }

export function SecurityControlDrawer({ record, onClose }: { record: OpsRecord; onClose: () => void }) {
  const createEvidence = async () => { if (!window.desktopAPI) { toast.error("Run the Windows desktop app to record audit-export evidence."); return; } try { await window.desktopAPI.recordSecurityAuditExport(record.id); window.dispatchEvent(new Event("ops-state-updated")); toast.success("Audit-export evidence recorded in the append-only log."); onClose(); } catch (error: any) { toast.error(error.message || "Could not record audit-export evidence."); } };
  return <Drawer><Header eyebrow="Security-control evidence" title={record.name || "Security control"} onClose={onClose} /><div className="flex-1 space-y-5 overflow-y-auto px-6 py-5"><section className="rounded-xl border border-slate-800 bg-slate-950/25 p-4"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-cyan-200" /><p className="text-sm font-semibold text-slate-100">Control evidence</p></div><p className="mt-3 text-sm text-slate-300">{record.evidence || "No evidence recorded."}</p><p className="mt-2 text-xs text-slate-500">Cadence: {record.cadence || "Not set"} · Owner: {record.owner || "Unassigned"}</p><Button onClick={createEvidence} className="mt-4 w-full bg-cyan-400 text-slate-950 hover:bg-cyan-300"><Download className="mr-2 h-4 w-4" />Record audit evidence export</Button></section><section className="rounded-xl border border-slate-800 bg-slate-950/25 p-4"><div className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-cyan-200" /><p className="text-sm font-semibold text-slate-100">Audit-export evidence</p></div><div className="mt-3 space-y-2">{(record.auditExports || []).length ? (record.auditExports || []).map((item: any) => <div key={item.id} className="rounded-lg border border-slate-800 p-3"><p className="text-xs font-semibold text-slate-200">{formatDate(item.generatedAt)}</p><p className="mt-1 text-xs text-slate-500">{item.eventCount} events · {item.generatedBy} · {item.scope}</p></div>) : <p className="text-xs text-slate-500">No export evidence has been recorded.</p>}</div></section></div></Drawer>;
}

export function DiagnosticsDrawer({ record, onClose }: { record: OpsRecord; onClose: () => void }) {
  const generate = async () => { if (!window.desktopAPI) { toast.error("Run the Windows desktop app to generate a diagnostics bundle."); return; } try { await window.desktopAPI.generateDiagnosticsBundle(record.id); window.dispatchEvent(new Event("ops-state-updated")); toast.success("Minimized diagnostics bundle metadata generated and audited."); onClose(); } catch (error: any) { toast.error(error.message || "Could not generate diagnostics metadata."); } };
  return <Drawer><Header eyebrow="Support diagnostics" title={record.name || "Diagnostics bundle"} onClose={onClose} /><div className="flex-1 space-y-5 overflow-y-auto px-6 py-5"><section className="rounded-xl border border-slate-800 bg-slate-950/25 p-4"><div className="flex items-center gap-2"><Stethoscope className="h-4 w-4 text-cyan-200" /><p className="text-sm font-semibold text-slate-100">Privacy-minimized diagnostics</p></div><p className="mt-3 text-sm text-slate-300">{record.summary || "No summary available."}</p><Button onClick={generate} className="mt-4 w-full bg-cyan-400 text-slate-950 hover:bg-cyan-300">Generate metadata bundle</Button></section><section className="rounded-xl border border-slate-800 bg-slate-950/25 p-4"><p className="text-sm font-semibold text-slate-100">Generated bundle history</p><div className="mt-3 space-y-2">{(record.bundles || []).length ? (record.bundles || []).map((bundle: any) => <div key={bundle.id} className="rounded-lg border border-slate-800 p-3"><p className="text-xs font-semibold text-slate-200">{formatDate(bundle.generatedAt)}</p><p className="mt-1 text-xs text-slate-500">{bundle.generatedBy} · {bundle.redaction}</p><p className="mt-1 text-xs text-slate-400">Students {bundle.recordCounts.students} · Sessions {bundle.recordCounts.sessions} · Incidents {bundle.recordCounts.incidents} · Audit events {bundle.recordCounts.auditEvents}</p></div>) : <p className="text-xs text-slate-500">No diagnostics bundle has been generated.</p>}</div></section></div></Drawer>;
}

export function ReconciliationDrawer({ record, onClose }: { record: OpsRecord; onClose: () => void }) {
  const [resolution, setResolution] = useState(record.resolution || "");
  const resolve = async () => { if (!resolution.trim()) { toast.error("Enter resolution evidence before closing this reconciliation."); return; } if (!window.desktopAPI) { toast.error("Run the Windows desktop app to resolve a reconciliation."); return; } try { await window.desktopAPI.resolveReconciliation(record.id, resolution); window.dispatchEvent(new Event("ops-state-updated")); toast.success("Reconciliation resolved and retained with evidence."); onClose(); } catch (error: any) { toast.error(error.message || "Could not resolve reconciliation."); } };
  return <Drawer><Header eyebrow="Integration reconciliation" title={record.title || "Reconciliation"} onClose={onClose} /><div className="flex-1 space-y-5 overflow-y-auto px-6 py-5"><section className="rounded-xl border border-slate-800 bg-slate-950/25 p-4"><p className="text-sm font-semibold text-slate-100">Run evidence</p><p className="mt-3 text-sm text-slate-300">{record.issue || "No issue recorded."}</p><p className="mt-2 text-xs text-slate-500">Integration: {record.integrationId || "Not linked"} · Source run: {record.sourceRunId || "Not linked"}</p><p className="mt-3 text-xs leading-5 text-cyan-200">Proposed: {record.proposedResolution || "No proposal recorded."}</p></section><section className="rounded-xl border border-slate-800 bg-slate-950/25 p-4"><p className="text-sm font-semibold text-slate-100">Resolution and closure</p><Textarea value={resolution} onChange={(event) => setResolution(event.target.value)} placeholder="Record validation samples, mapping change, approval, and operator evidence" className="mt-3 min-h-32 border-slate-700 bg-slate-950 text-slate-100" /><Button onClick={resolve} disabled={record.status === "resolved" || record.status === "cancelled"} className="mt-3 w-full bg-cyan-400 text-slate-950 hover:bg-cyan-300 disabled:opacity-40">Resolve reconciliation</Button>{record.resolvedAt ? <p className="mt-3 text-xs text-emerald-200">Resolved {formatDate(record.resolvedAt)} by {record.resolvedBy}</p> : null}</section></div></Drawer>;
}
