const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("desktopAPI", {
  getState: () => ipcRenderer.invoke("ops:get-state"),
  changeRole: (role) => ipcRenderer.invoke("ops:change-role", role),
  create: (entity, payload) => ipcRenderer.invoke("ops:create", entity, payload),
  update: (entity, id, patch) => ipcRenderer.invoke("ops:update", entity, id, patch),
  remove: (entity, id) => ipcRenderer.invoke("ops:delete", entity, id),
  addSopVersion: (id, payload) => ipcRenderer.invoke("ops:add-sop-version", id, payload),
  generateReportSnapshot: (id, schedule) => ipcRenderer.invoke("ops:generate-report-snapshot", id, schedule),
  resolveImportRun: (sourceId, runId, remediation) => ipcRenderer.invoke("ops:resolve-import-run", sourceId, runId, remediation),
  profileStudentDataset: (name, csvText) => ipcRenderer.invoke("ops:profile-student-dataset", name, csvText),
  commitStudentDataset: (datasetId) => ipcRenderer.invoke("ops:commit-student-dataset", datasetId),
  prepareSessionEvaluation: (sessionId, rubricId) => ipcRenderer.invoke("ops:prepare-session-evaluation", sessionId, rubricId),
  generateBusinessReview: (period) => ipcRenderer.invoke("ops:generate-business-review", period),
  requestAnalystRun: (payload) => ipcRenderer.invoke("ops:request-analyst-run", payload),
  validateIntegration: (id) => ipcRenderer.invoke("ops:validate-integration", id),
  queueIntegrationSync: (id) => ipcRenderer.invoke("ops:queue-integration-sync", id),
  runGuardedIntegrationSync: (id) => ipcRenderer.invoke("ops:run-guarded-integration-sync", id),
  resolveReconciliation: (id, resolution) => ipcRenderer.invoke("ops:resolve-reconciliation", id, resolution),
  runAutomation: (id, overrideNote) => ipcRenderer.invoke("ops:run-automation", id, overrideNote),
  recordSecurityAuditExport: (id) => ipcRenderer.invoke("ops:record-security-audit-export", id),
  generateDiagnosticsBundle: (id) => ipcRenderer.invoke("ops:generate-diagnostics-bundle", id),
  importStudents: (csvText) => ipcRenderer.invoke("ops:import-students", csvText),
  exportCsv: (payload) => ipcRenderer.invoke("ops:export-csv", payload),
  resetDemo: () => ipcRenderer.invoke("ops:reset-demo"),
  openExternal: (target) => ipcRenderer.invoke("ops:open-external", target),
});
