/*
 * GENERATED by scripts/colophon.mjs — do not edit by hand.
 *
 * Counted from this repository at build time, so the site's statements about
 * itself cannot drift from what it actually is.
 */
export const colophon = {
  "dependencies": 9,
  "tests": 150,
  "testFiles": 11,
  "sourceFiles": 42,
  "lines": 8023,
  "bundleKb": 461,
  "stack": [
    "React",
    "TypeScript",
    "Vite",
    "wouter"
  ]
} as const;
